-- ---------------------------------------------------------------------------
-- Server-side re-grading for hosted HTML tests.
--
-- Hosted tests grade themselves in the browser and POST the score, so before
-- this migration the server had no answer key and could not check the claim.
-- A student could open devtools and post a perfect score without answering:
--
--   fetch(LEXORA_TEST.submitUrl,{method:"POST", ...,
--     body:JSON.stringify({attemptId:LEXORA_TEST.attemptId,
--                          skills:[{skill:"GRAMMAR",correct:30,total:30}]})})
--
-- This table gives the server its own key. When a key exists for a test, the
-- submit route (src/app/api/tests/html/submit/route.ts) ignores the client's
-- claimed score entirely and re-grades the submitted ANSWERS itself.
--
-- HONEST LIMIT: the questions and their correct answers still ship inside the
-- self-contained HTML, so a student who reads the page source can look the
-- answers up. This closes score FORGERY (claiming a score you did not earn); it
-- does not make a hosted test unreadable. Assessments that must be tamper-proof
-- belong on the server-graded /t/<token> rail, where answer_key never leaves
-- the database (migrations 0018 + 0019).
--
-- Additive: new table only. No existing row is read, changed or dropped.
-- ---------------------------------------------------------------------------

create table if not exists html_test_answer_keys (
  html_test_id uuid primary key references html_tests (id) on delete cascade,
  -- Shape: { "version": 1, "count": <questions served per attempt>,
  --          "skill": <skill_area>,
  --          "items": { "<question id>": { "t": "mc"|"wo"|"tr",
  --                                        "a": [<accepted answer strings>] } } }
  --
  -- `count` is the denominator the server insists on. Without it a tampered
  -- client could submit a single correct answer and score 1/1 = 100 %.
  -- Answers are compared as TEXT, never as choice indexes: hosted tests shuffle
  -- their options per attempt, so an index would grade the wrong option.
  answer_key jsonb not null,
  -- Rollout switch. false = the key exists but a payload without answers is
  -- still accepted as a self-report (lets a key land before the updated test
  -- file is live). true = answers are mandatory, so omitting them cannot be
  -- used to dodge re-grading.
  require_answers boolean not null default false,
  created_at timestamptz not null default now()
);

alter table html_test_answer_keys enable row level security;

-- No policy is created, on purpose: with RLS enabled and zero policies the
-- table is invisible to anon/authenticated through PostgREST. Only the
-- service-role client (the submit route) can read it. Belt and braces:
revoke all on html_test_answer_keys from authenticated, anon;

-- ---------------------------------------------------------------------------
-- Key for "Present Continuous — Beginner Test"
-- (html_test 8a6f72d4-7c49-4c32-ad7c-07522f2bd279,
--  storage_path .../present-continuous-beginner.html).
--
-- Generated by executing the LIVE bucket file's own question-definition code,
-- so the key cannot drift from the questions a student actually sees. 30 fixed
-- questions: 12 multiple choice, 10 word order, 8 translation. Ids are the
-- 0-based question index — that file shuffles nothing, so the index is stable.
--
-- NOTE: this is deliberately keyed to the file IN THE BUCKET, which is NOT the
-- same test as hosted-tests/present-continuous-beginner.html in this repo (that
-- one is an unshipped random-bank rewrite with different questions). Re-key
-- before ever replacing the bucket object.
--
-- Matched on storage_path rather than a hardcoded uuid so the migration is
-- environment-independent: on a database where that test does not exist the
-- insert affects no rows and the feature stays dormant.
-- ---------------------------------------------------------------------------

insert into html_test_answer_keys (html_test_id, answer_key, require_answers)
select h.id, '{"version":1,"count":30,"skill":"GRAMMAR","items":{"0":{"t":"mcq","a":["am reading"]},"1":{"t":"mcq","a":["isn''t watching"]},"2":{"t":"mcq","a":["Are"]},"3":{"t":"mcq","a":["writing"]},"4":{"t":"mcq","a":["are making"]},"5":{"t":"mcq","a":["sleeping"]},"6":{"t":"mcq","a":["making"]},"7":{"t":"mcq","a":["running"]},"8":{"t":"mcq","a":["sitting"]},"9":{"t":"mcq","a":["lying"]},"10":{"t":"mcq","a":["aren''t"]},"11":{"t":"mcq","a":["are"]},"12":{"t":"order","a":["Sara is studying English now"]},"13":{"t":"order","a":["the children are playing in the park"]},"14":{"t":"order","a":["Jamshid is wearing a blue shirt"]},"15":{"t":"order","a":["I am not wearing a jacket"]},"16":{"t":"order","a":["Malika is not working today"]},"17":{"t":"order","a":["we are not watching television"]},"18":{"t":"order","a":["are you waiting for the bus","you are waiting for the bus"]},"19":{"t":"order","a":["is the teacher speaking now","the teacher is speaking now"]},"20":{"t":"order","a":["why is the baby crying"]},"21":{"t":"order","a":["what are they making"]},"22":{"t":"trans","a":["Aziza is reading a book now","Aziza is reading a book"]},"23":{"t":"trans","a":["Jasur is not sleeping now","Jasur is not sleeping"]},"24":{"t":"trans","a":["Are the children running in the park","Are the kids running in the park"]},"25":{"t":"trans","a":["What are you doing now","What are you doing"]},"26":{"t":"trans","a":["I am not waiting for the bus now","I am not waiting for the bus"]},"27":{"t":"trans","a":["Ali is sitting on a chair","Ali is sitting on the chair"]},"28":{"t":"trans","a":["Are they swimming now","Are they swimming"]},"29":{"t":"trans","a":["Why is the baby crying"]}}}'::jsonb, true
from html_tests h
where h.storage_path like '%present-continuous-beginner.html'
on conflict (html_test_id) do update
  set answer_key      = excluded.answer_key,
      require_answers = excluded.require_answers;
